# Autogenerated wrapper script for qiskit_ibm_runtime_jll for x86_64-linux-gnu
export libqiskit_ibm_runtime

using Qiskit_jll
JLLWrappers.@generate_wrapper_header("qiskit_ibm_runtime")
JLLWrappers.@declare_library_product(libqiskit_ibm_runtime, "libqiskit_ibm_runtime.so")
function __init__()
    JLLWrappers.@generate_init_header(Qiskit_jll)
    JLLWrappers.@init_library_product(
        libqiskit_ibm_runtime,
        "lib/libqiskit_ibm_runtime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
